### ISSUE TITLE
Bug CentCom to un-slash the AME budget (aka fucking obliterate the nerf because of how often Arcadis is lowpop)

### ISSUE THREAD

**Issue by Wyatt90** [Guloveos/arc-station-14#16]
**Describe the feature you are requesting in as much detail as possible.**
The AME fuel is apparently 500 now (can't tell if that was ANOTHER nerf or something different) on top of the AME being much weaker. Arcadis is very consistently lowpop, so I feel it'd be a good idea to revert the nerfs against the antimatter engine.

Deleted the "how I feel it could be added section" as I have no actual idea how the game actually fucking works on a technical level.
**Additional context**

**Comment by TheDoctor1977** [comment]
we’ll have to find where specifically it got merged but this should be doable
@Guloveos if you haven’t found the PRs upstream by tomorrow let me know and i’ll find them

**Comment by bruhmogus** [comment]
as much as i hate to say it, we SHOULD unmerge the ame nerf, along with Chief-Engineer's overload alert removal

**Comment by Guloveos** [comment]
Finally god centcom to pay us more
