### ISSUE TITLE
Abyss creatures can be butchered, but dont give anything, don't disappear, and don't make blood

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/arc-station-14#17]
## Description
Title

**Reproduction**
Step 1. Kill an abyss creautre
Step 2. Butcher
Step 3. Cry

**Screenshots**
![20240730193415_1](https://github.com/user-attachments/assets/01406208-9bfd-40e8-b6db-4a424486038a)

**Additional context**
Clientside only butcherable component?

**Comment by Guloveos** [comment]
Fixed
