### ISSUE TITLE
Add a Central Command intern jumpsuit to the fork

### ISSUE THREAD

**Issue by Wyatt90** [Guloveos/arc-station-14#18]
Okay so, I REALLY want to contribute something besides just unmerging nerfs for the AME n' shit.
So I asked a whole bunch of admemes in dchat the following question: "do yall think a CentCom intern jumpsuit will be used very often" (exact quote). Moose and Doctor responded, respectively, "Bro I would use that all the time" and "i would use that yeah"
So here we are, this issue here. Not actually a legit issue, just a feature request.

I'm pretty sure this COULD be made with just a resprited and re-YAML'd grey jumpsuit but I know jack shit about the game's internal workings so... yeah.

**Comment by TheDoctor1977** [comment]
afaik gul is on a sort of hiatus from fork work so this may not get done very soon but for now you could try it yourself, wizden has some great guides on it
https://docs.spacestation14.com/en/general-development/setup.html

**Comment by Guloveos** [comment]
added
