### ISSUE TITLE
The SecTech on the Leapfrog is still security locked

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/arc-station-14#23]
## Description
This means that the mercs are unable to get anything from it. INCLUDING HANDCUFFS.

**Reproduction**
Step 1. Summon the Leapfrog
Step 2. Get a merc PDA/ID
Step 3. Use the SecTech
Step 4. Die

**Screenshots**
![20240818105203_1](https://github.com/user-attachments/assets/b5e34504-4a38-4b2c-9d7b-380194f9fd5b)

**Additional context**
Probably a leftover from when mercs had stolen secoff ids

**Comment by TheDoctor1977** [comment]
killing myself!
this needs a custom merc locked prototype made

**Comment by Wyatt90** [comment]
maybe if you don't want a prototype you could give mercs an emag or something to break the access requirements??? but then that'd make it easier for the targets to get gear from the sectech if they break out so maybe but i dunno that might work???

**Comment by Guloveos** [comment]
Ill make a custom Vending machine for the mercs

**Comment by TheDoctor1977** [comment]
> maybe if you don't want a prototype you could give mercs an emag or something to break the access requirements??? 

i hate to pull the “muh vision for the game” card, but giving mercs any kind of access breaking technology (outside of literally just stealing an ID) goes against the core idea behind the antag and fucks with all sorts of planning

**Comment by Wyatt90** [comment]
okay then

**Comment by Guloveos** [comment]
Fixed
