### ISSUE TITLE
Universal IDs don't have merc and NTPD access. Again.

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/arc-station-14#24]
## Description
They still don't have it.

**Reproduction**
Step 1. Spawn a universal ID
Step 2. Try to open an NTPD door
Step 3. Mald

**Screenshots**
![20240818105719_1](https://github.com/user-attachments/assets/4ab49682-0729-432b-89b4-59919ad2d9b3)

**Additional context**
RAAAGH

**Comment by TheDoctor1977** [comment]
ok chat let’s kill @Guloveos

**Comment by Guloveos** [comment]
DONT KILL ME I fixed it!
