### ISSUE TITLE
Revert current Security jumpsuits to what they were before

### ISSUE THREAD

**Issue by Wyatt90** [Guloveos/arc-station-14#25]
The current security jumpsuits kinda suck (at least in my and Fed's opinion) and look too much like red jumpsuits. If possible could we get them reverted back to their maroonish look?

**Comment by Wyatt90** [comment]
https://github.com/space-wizards/space-station-14/pull/29082 so it isn't hell to hunt down later

**Comment by Erisfiregamer1** [comment]
Commit will be reverted with the rest of my bigchange PRs.

**Comment by TheDoctor1977** [comment]
> Commit will be reverted with the rest of my bigchange PRs.

make sure you also grab the security webbing resprite

**Comment by TheDoctor1977** [comment]
@Erisfiregamer1 you've been reverting stuff make sure this doesn't get forgotten
