### ISSUE TITLE
ERPDrobe is missing entries

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/arc-station-14#26]
## Description
The ERPDrobe is missing handcuffs and cat ears.

**Reproduction**
Step 1. spawn ERPDrobe
Step 2. Cry

**Screenshots**
![20240819200536_1](https://github.com/user-attachments/assets/62ca7547-84e8-485a-b0f5-8aa3495e2a83)

**Additional context**
god has abandoned us

**Comment by Wyatt90** [comment]
honestly glad the handcuffs aren't there but the cat ears should probably be brought back into existence

**Comment by Guloveos** [comment]
Fixed
