### ISSUE TITLE
meta hardsuit light is fucky

### ISSUE THREAD

**Issue by TheDoctor1977** [Guloveos/arc-station-14#27]
it's supposed to be a headlamp shining from the side (that little bulge on the left of the helmet) sorta like the raid suit but the actual lens flare is missing
current:
![image](https://github.com/user-attachments/assets/82f6b3d7-df2f-42b7-abd2-6423f0f1e953)

intended effect:
![image](https://github.com/user-attachments/assets/4818438a-6171-4b3e-98d7-1d7df1da9ff6)

also the light range could do with a bit of an extension to match the raid suit

**Comment by Guloveos** [comment]
![image](https://github.com/user-attachments/assets/5557f71b-bbad-4b25-9580-c461c80f2fcf)

**Comment by TheDoctor1977** [comment]
rahhh it still doesn't have the lens flare on the side

**Comment by Guloveos** [comment]
added
