### ISSUE TITLE
capitalized shit master issue

### ISSUE THREAD

**Issue by TheDoctor1977** [Guloveos/arc-station-14#28]
i will individually screenshot every one of these if i have to
![image](https://github.com/user-attachments/assets/099c2cd3-88c1-4772-aa0a-5ac59d4dd4e1)
![image](https://github.com/user-attachments/assets/434cf3e6-b5ca-4353-8f19-fc7da90667a8)
![image](https://github.com/user-attachments/assets/c5ca689d-18a3-44bd-aa75-5a8573f24b22)
![image](https://github.com/user-attachments/assets/fcc1da95-e6b1-4796-80d3-ddad5bc11394)
![image](https://github.com/user-attachments/assets/c92ca49e-a576-4203-8128-c9062f217b2e)

**Comment by Guloveos** [comment]
Fixed

**Comment by TheDoctor1977** [comment]
plushie is not a proper noun, for approving this you will be turned into paste
![IMG_8106](https://github.com/user-attachments/assets/21a89a67-992c-4801-85ea-d7ff80283036)

**Comment by Guloveos** [comment]
son of a bitch

**Comment by Guloveos** [comment]
I see nothing wrong with this
