### ISSUE TITLE
Zombie Defense Event

### ISSUE THREAD

**Issue by TheDoctor1977** [Guloveos/arc-station-14#33]
[as suggested by ttv_todthepotato on Discord](https://discord.com/channels/1211854877752557598/1275974439376523336)

this would be a new event that would generally be PVE, although the zombies should be ghost roles for permadead players

- [x] custom/stronger infected
- [x] equipment shop with sale system (this should probably be a computer instead of an item)
- [x] some way to enforce a safe zone for the equipment shop between waves
- [x] "horde spawner" to generate a large group of zombies at once

**Comment by Guloveos** [comment]
Gonna use the flesh as the zombies going forward

**Comment by Guloveos** [comment]
Holy shit this has blown up to a whole new game mode

**Comment by Guloveos** [comment]
mostly done I just gotta fix one bug
