### ISSUE TITLE
Feature Request : "Basic/Advanced Ballistics" Research

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/arc-station-14#34]
## Description
The ability to research basic (roundstart like lecter, mk 58, and drozd) and advanced (more powerful guns like the wt550 or revolvers) through science, to allow the fabrication of ballistic weapons if they're all stolen or lost, preferably fabricable through the secfab

**Comment by TheDoctor1977** [comment]
> to allow the fabrication of ballistic weapons if they're all stolen or lost

this is an issue that doesn't exist
you can buy them at cargo if this somehow happens

**Comment by bruhmogus** [comment]
> > to allow the fabrication of ballistic weapons if they're all stolen or lost
> 
> this is an issue that doesn't exist you can buy them at cargo if this somehow happens

wizden is nerfing cargo to the point it practically wont exist, we should prob give them some way (maybe tech disks) to fabricate them

**Comment by Guloveos** [comment]
Not adding this right now, we will see how rounds work after the cargo change. If its dog shit then ill add it

**Comment by TheDoctor1977** [comment]
closing to clean up issue list, will revisit this after cargo changes
