### ISSUE TITLE
Feature request: Cluster-nuclear options

### ISSUE THREAD

**Issue by Wyatt90** [Guloveos/arc-station-14#38]
## Description
SOME of the admins really fucking like the nuclear option. Like. A lot. So I figure, hey, what if we made a cluster nuclear option like the clusterbang? It'd be funny.

**Comment by Guloveos** [comment]
Seth is gonna add it >:)

**Comment by Wyatt90** [comment]
Probably no stopping this from being added. Guh?

**Comment by Creatorbot01** [comment]
Ya think?

**Comment by TheDoctor1977** [comment]
funny....... 

we will be accepting no further discussion

**Comment by bruhmogus** [comment]
this is (unfortunately) added, closing
