### ISSUE TITLE
AI cannot access high security doors

### ISSUE THREAD

**Issue by Wyatt90** [Guloveos/arc-station-14#39]
## Reproduction
Try to fuck with a high security door
Realize you can't see "Open actions" or interact with it besides inspecting and shit
Cry a river

**Comment by TheDoctor1977** [comment]
this is something that needs to be fixed upstream https://github.com/space-wizards/space-station-14/issues/31597

**Comment by Wyatt90** [comment]
FFFFUUUCCCKKKK
