### ISSUE TITLE
Admin Tool: Syndicate and Nanotrasen Bluespace beacons

### ISSUE THREAD

**Issue by TheDoctor1977** [Guloveos/arc-station-14#40]
### This is a long term request. Enjoy your vacation, Gul.
Currently, there is no effective IC way to deliver items to players without going through cargo. Therefore, I propose a simple beacon system for bluespacing crates. Here is roughly how it should work, on the user end:
1. Admin packs at least one crate of items in their sandbox area
2. Admin tags the crate(s) with the beacon
3. Admin sets the beacon down somewhere on-station
4. After a set delay, the crate(s) is bluespaced with a sound and effect (the bluespace locker effect can be copied for this)

Off the top of my head, I can think of a few modifiers the beacon will need:
- The ability to make the beacon uninteractable and invisible
- A "silent mode" that removes the visual and audio effect
- A toggle to allow players to activate it manually to, for example, call a prepared supply drop on demand.

Although I distinguish between NT and Syndicate in the title, these beacons should be mechanically identical, only with different sprites.

Will edit this issue if I think of more.

**Comment by Creatorbot01** [comment]
Honestly this is my theory that i does not test yet but you can vv fulton to be invisible and also you can remove the item comp so that people cant just yoink it(you cant drag an actice fulton without unfolding it). I think you can remove the ability to unfold but i havent tried it anyway yea. That just my opinion.

**Comment by Guloveos** [comment]
Added it, will still work on the other parts tho
