### ISSUE TITLE
Amnestic Autoinjector

### ISSUE THREAD

**Issue by TheDoctor1977** [Guloveos/arc-station-14#42]
A specialized injector for Amnestics. This issue intends to resolve an issue from The NTPD Infosheet, that being: "These compounds are only available to NTPD operatives. Non-NTPD crew do not have the training to use them, as the devices used to administer them are intentionally complicated and extremely advanced."

The injector should have a unique sprite from both regular autoinjector pens (as it is refillable and reusable), hyposprays (it is more advanced), and syringes (see previous). It should have mechanically infinite chemicals, and the ability to switch between amnestic/mnestic types at will. If a non-NTPD user (defined by #43) attempts to inject someone or modify the settings on the autoinjector, they should receive a "You don't know how to use this!" popup. If they hold it for over 30 seconds, it should shock them (MV damage with doubled stun time).

When this is implemented, all the amnestic syringes and pills should be removed to prevent accidental spawning.

Checklist: 
- [ ] #43
- [ ] A way to restrict the usage of the injector based off the NTPDOperative component
- [ ] Sprite (in-hand and item!) - I have no particular vision for this, outside of it appearing as a "normal" NT medical tool, since it will be used by both suited and undercover operatives
- [ ] Mechanical aspects - infinite injection, switchable chem output

**Comment by a-person5660** [comment]
so you want it to have an infinate amount of amnestics and mnestics or an infinate storage?

**Comment by a-person5660** [comment]
you can use the debug hypopen until this gets added. it looks like a gorlex hypo, has no cooldown and 1000u capacity iirc.

**Comment by TheDoctor1977** [comment]
> so you want it to have an infinate amount of amnestics and mnestics or an infinate storage?

It should have an infinite amount of a selected amnestic/mnestic, and a toggle to switch between them.

**Comment by Guloveos** [comment]
I actually have no idea how to do 90% of this

**Comment by a-person5660** [comment]
I would just make a copy of the hypo component and hard code in all the stuff you need. It's a tiny repo, you don't need to do everything in yaml.

**Comment by Guloveos** [comment]
To bad I dont know how to code

**Comment by fl215** [comment]
restricting items to certain characters is absolutely stupid

**Comment by TheDoctor1977** [comment]
issue cleanup - this is pretty big scope creep and overly complicated, can be revisited later
closing along with #43
