### ISSUE TITLE
FBI's Other Pile of Random Shit because Mercs

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/arc-station-14#5]
- [x] Merc ID has no job title
- [x] Universal access id lacks NTPD access
- [x] Universal access id lacks merc access
- [x] Universal access config. lacks mercs, but can see NTPD
- [x] Merc channel is :1111
- [x] ALL merc shit needs uncapitalization in their name
- [x] Agent IDs cham is near unusable with previews
- [x] Shorten ENLIST TO THE URBAN SOLUTIONS to another ENLIST. poster

**Comment by Guloveos** [comment]
Cant find a way to make the charm not have NTPD/merc stuff

**Comment by TheDoctor1977** [comment]
> Cant find a way to make the charm not have NTPD/merc stuff

![image](https://github.com/Guloveos/arc-station-14/assets/108845723/3d026ca6-3409-409e-886f-bbe798a11c84)

**Comment by Guloveos** [comment]
still doesn't work
we will just have to live with it

**Comment by TheDoctor1977** [comment]
afaik this is resolved
