### ISSUE TITLE
Unmerge request : Readd shock collars

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/arc-station-14#50]
## Description
We should keep them for saw traps and bomb collars eventually

**Comment by TheDoctor1977** [comment]
if readded they should not be normally crew-obtainable because the upstream concerns about people being 𝓯𝓻𝓮𝓪𝓴𝔂 with them are still valid

**Comment by Creatorbot01** [comment]
Watch as me set the damage heat value to 500 to ash em before banning em.

**Comment by bruhmogus** [comment]
they got re-added, closing
