### ISSUE TITLE
Moose mask has no antlers :(

### ISSUE THREAD

**Issue by Madformoose** [Guloveos/arc-station-14#6]
## Description
Moose mask got no antlers, on either the item sprite or on the character. MEESE HAVE ANTLERS GAWD DARNIT!!!!

**Reproduction**
Look at cool moose mask, observe no antlers, cry, make an issue on github.

**Screenshots**
![image](https://github.com/Guloveos/Arcadis-station-14/assets/148000477/1e0337d8-32f7-4e52-a3ad-4e6c77246f33)

**Additional context**
Also station AI when?

**Comment by Guloveos** [comment]
Moose. do it your self L

**Comment by Madformoose** [comment]
Gul do your job and fork the forks you utter GREMLIN
